use crate::webhook::Vote;
use hmac::{Hmac, Mac};
use serde::Deserialize;
use sha2::Sha256;
use std::{
  collections::HashMap,
  time::{SystemTime, UNIX_EPOCH},
};

/// Maximum accepted clock difference between the `t=` timestamp in the
/// signature header and this machine, in seconds. Rejects replayed requests.
const SIGNATURE_TOLERANCE_SECS: u64 = 300;

/// A dispatched [Top.gg](https://top.gg) v1 webhook event envelope
/// (`vote.create` / `webhook.test`).
#[must_use]
#[derive(Clone, Debug, Deserialize)]
pub struct VoteEvent {
  /// The event type, e.g. `vote.create` or `webhook.test`.
  #[serde(rename = "type")]
  pub kind: String,

  /// The event payload.
  pub data: VoteEventData,
}

/// The `data` object of a v1 webhook event.
#[must_use]
#[derive(Clone, Debug, Deserialize)]
pub struct VoteEventData {
  /// The vote's ID on Top.gg.
  #[serde(default)]
  pub id: Option<String>,

  /// The vote's weight (2 during weekend multipliers, 1 otherwise).
  /// Absent on `webhook.test` events.
  #[serde(default)]
  pub weight: Option<u64>,

  /// When the vote was created (ISO 8601). Absent on `webhook.test` events.
  #[serde(default)]
  pub created_at: Option<String>,

  /// When the vote expires (ISO 8601). Absent on `webhook.test` events.
  #[serde(default)]
  pub expires_at: Option<String>,

  /// The project (bot/server) that received the vote.
  #[serde(default)]
  pub project: Option<VoteEventProject>,

  /// Query strings found on the vote page.
  #[serde(default)]
  pub query: HashMap<String, String>,

  /// The user who voted.
  pub user: VoteEventUser,
}

/// The `data.project` object of a v1 webhook event.
#[must_use]
#[derive(Clone, Debug, Deserialize)]
pub struct VoteEventProject {
  /// The project's ID on Top.gg.
  #[serde(default)]
  pub id: Option<String>,

  /// The project type: `bot` or `server`.
  #[serde(default, rename = "type")]
  pub kind: Option<String>,

  /// The platform the project lives on, e.g. `discord`.
  #[serde(default)]
  pub platform: Option<String>,

  /// The project's ID on its platform (e.g. the Discord bot/guild ID).
  #[serde(default)]
  pub platform_id: Option<String>,
}

/// The `data.user` object of a v1 webhook event.
#[must_use]
#[derive(Clone, Debug, Deserialize)]
pub struct VoteEventUser {
  /// The user's ID on Top.gg.
  #[serde(default)]
  pub id: Option<String>,

  /// The user's ID on the project's platform (e.g. their Discord ID).
  pub platform_id: String,

  /// The user's name.
  #[serde(default)]
  pub name: Option<String>,

  /// The user's avatar URL.
  #[serde(default)]
  pub avatar_url: Option<String>,
}

impl VoteEvent {
  /// Converts this v1 event into the legacy [`Vote`] structure so existing
  /// [`VoteHandler`][crate::VoteHandler] implementations keep working
  /// unchanged. Returns [`None`] if the voter's platform ID is not numeric.
  #[must_use]
  pub fn into_vote(self) -> Option<Vote> {
    let voter_id = self.data.user.platform_id.parse().ok()?;

    let (receiver_id, is_server) = match &self.data.project {
      Some(project) => (
        project
          .platform_id
          .as_deref()
          .and_then(|id| id.parse().ok())
          .unwrap_or(0),
        project.kind.as_deref() == Some("server"),
      ),
      None => (0, false),
    };

    Some(Vote {
      receiver_id,
      voter_id,
      is_server,
      is_test: self.kind == "webhook.test",
      is_weekend: self.data.weight.unwrap_or(1) >= 2,
      query: self.data.query,
    })
  }
}

/// Verifies a v1 `x-topgg-signature` header (`t={unix timestamp},v1={hex
/// HMAC-SHA256 of "{timestamp}.{raw body}"}`) against the `whs_`-prefixed
/// webhook secret generated by Top.gg. Comparison is constant-time and the
/// timestamp must be within [`SIGNATURE_TOLERANCE_SECS`] of the current time.
#[must_use]
pub fn verify_v1_signature(secret: &str, signature_header: &str, raw_body: &[u8]) -> bool {
  let mut timestamp: Option<&str> = None;
  let mut signature: Option<&str> = None;

  for part in signature_header.split(',') {
    match part.trim().split_once('=') {
      Some(("t", value)) => timestamp = Some(value),
      Some(("v1", value)) => signature = Some(value),
      _ => {}
    }
  }

  let (Some(timestamp), Some(signature)) = (timestamp, signature) else {
    return false;
  };

  let Ok(timestamp_secs) = timestamp.parse::<u64>() else {
    return false;
  };

  let now = SystemTime::now()
    .duration_since(UNIX_EPOCH)
    .map(|d| d.as_secs())
    .unwrap_or(0);

  if now.abs_diff(timestamp_secs) > SIGNATURE_TOLERANCE_SECS {
    return false;
  }

  let Ok(expected) = hex::decode(signature) else {
    return false;
  };

  let Ok(mut mac) = Hmac::<Sha256>::new_from_slice(secret.as_bytes()) else {
    return false;
  };

  mac.update(timestamp.as_bytes());
  mac.update(b".");
  mac.update(raw_body);

  mac.verify_slice(&expected).is_ok()
}

#[cfg(test)]
mod tests {
  use super::*;

  fn sign(secret: &str, timestamp: u64, body: &str) -> String {
    let mut mac = Hmac::<Sha256>::new_from_slice(secret.as_bytes()).unwrap();
    mac.update(format!("{timestamp}.{body}").as_bytes());
    let sig = mac.finalize().into_bytes();
    format!("t={timestamp},v1={}", hex::encode(sig))
  }

  fn now() -> u64 {
    SystemTime::now()
      .duration_since(UNIX_EPOCH)
      .unwrap()
      .as_secs()
  }

  #[test]
  fn accepts_valid_signature() {
    let body = r#"{"type":"vote.create","data":{"user":{"platform_id":"1"}}}"#;
    let header = sign("whs_test", now(), body);
    assert!(verify_v1_signature("whs_test", &header, body.as_bytes()));
  }

  #[test]
  fn rejects_wrong_secret_and_tampered_body() {
    let body = r#"{"type":"vote.create","data":{"user":{"platform_id":"1"}}}"#;
    let header = sign("whs_test", now(), body);
    assert!(!verify_v1_signature("whs_other", &header, body.as_bytes()));
    assert!(!verify_v1_signature("whs_test", &header, b"tampered"));
  }

  #[test]
  fn rejects_stale_timestamp_and_garbage() {
    let body = "{}";
    let stale = sign("whs_test", now() - 3600, body);
    assert!(!verify_v1_signature("whs_test", &stale, body.as_bytes()));
    assert!(!verify_v1_signature("whs_test", "not-a-header", body.as_bytes()));
    assert!(!verify_v1_signature("whs_test", "t=abc,v1=zz", body.as_bytes()));
  }

  #[test]
  fn converts_vote_create_into_vote() {
    let event: VoteEvent = serde_json::from_str(
      r#"{
        "type": "vote.create",
        "data": {
          "id": "808499215864008704",
          "weight": 2,
          "created_at": "2026-02-09T00:47:14+00:00",
          "expires_at": "2026-02-09T12:47:14+00:00",
          "project": {"id": "1", "type": "bot", "platform": "discord", "platform_id": "160105994217586689"},
          "query": {"key1": "value"},
          "user": {"id": "topgg", "platform_id": "661200758510977084", "name": "user", "avatar_url": null}
        }
      }"#,
    )
    .unwrap();
    let vote = event.into_vote().unwrap();
    assert_eq!(vote.voter_id, 661200758510977084);
    assert_eq!(vote.receiver_id, 160105994217586689);
    assert!(vote.is_weekend);
    assert!(!vote.is_test);
    assert!(!vote.is_server);
  }

  #[test]
  fn converts_webhook_test_into_test_vote() {
    let event: VoteEvent = serde_json::from_str(
      r#"{"type":"webhook.test","data":{"user":{"platform_id":"42"},"project":{"type":"bot","platform_id":"7"}}}"#,
    )
    .unwrap();
    let vote = event.into_vote().unwrap();
    assert!(vote.is_test);
    assert!(!vote.is_weekend);
    assert_eq!(vote.voter_id, 42);
  }
}
